### PR TITLE
add archive command

### PR DESCRIPTION
**Pull request by Bimi05**
well the command is already made but I thought of just adding it here so it's in the repo for people to copy it if needed :/

### CODE REVIEW

**Comment by capslock321** [comment]
You can maybe use with open:
```py
with open("archived.md") as file:
    file.write(data)
```
In contrast to:
```pay
f = open("file.md")
f.write(data)
f.close()
```
This removes the need to check if the file is there, and manually closing the file.

**Comment by Seniatical** [comment]
`\n\n` seems a bit large of a gap considering i use `\n`

**Comment by Bimi05** [comment]
well from what I've tested the file looks like it has a double `\n` which is why I used it. also the first option sounds quite better I don't know if I can use the async with or just with

**Review by capslock321 — APPROVED** [review]
Seems good to me, how about u @Seniatical

**Comment by Seniatical** [comment]
LGTM

**Pull request merged**
